# 1. Úkoly

## 1.1 `ndarray`

1. Jak zjistit velikost paměti libovolného pole? Vyzkoušejte na `a = np.array([1, 2, 3])`. Otestujte různé datové typy (`dtype`), například `np.int32`, `np.float64`, `np.complex128`.


In [3]:
import numpy as np

dtypes = [np.int32, np.float64, np.complex128]

for dt in dtypes:
    a = np.array([1, 2, 3], dtype=dt)
    print(f"dtype: {dt}")
    print(f"  itemsize: {a.itemsize} B")
    print(f"  size: {a.size}")
    print(f"  nbytes: {a.nbytes} B")
    print()

dtype: <class 'numpy.int32'>
  itemsize: 4 B
  size: 3
  nbytes: 12 B

dtype: <class 'numpy.float64'>
  itemsize: 8 B
  size: 3
  nbytes: 24 B

dtype: <class 'numpy.complex128'>
  itemsize: 16 B
  size: 3
  nbytes: 48 B



2. Zjistěte počet rozměrů, velikosti v jednotlivých rozměrech a celkový počet prvků v poli `a`.


In [4]:
print("Počet rozměrů:", a.ndim)
print("Velikosti rozměrů:", a.shape)
print("Počet prvků:", a.size)

Počet rozměrů: 1
Velikosti rozměrů: (3,)
Počet prvků: 3


3. Zjistěte typ prvků v poli `a` a velikost jednoho prvku v bajtech.


In [5]:
print("Datový typ:", a.dtype)
print("Velikost prvku:", a.itemsize, "B")

Datový typ: complex128
Velikost prvku: 16 B


4. Vytvořte NumPy pole `b` se stejnými rozměry jako `a`, ale s typem `np.float32`.


In [6]:
b = a.astype(np.float32)

C:\Users\vitek\AppData\Local\Temp\ipykernel_29332\986135016.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  b = a.astype(np.float32)


5. Přetypujte pole `a` na `np.float32` a uložte výsledek do pole `c`.


In [7]:
c = a.astype(np.float32)

C:\Users\vitek\AppData\Local\Temp\ipykernel_29332\27227761.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  c = a.astype(np.float32)


6. Vytvořte pole `d` s typem `np.datetime64` a uložte do něj datum `"2023-12-01"`.


In [8]:
d = np.array("2023-12-01", dtype=np.datetime64)

7. Vytvořte pole `e` se složeným typem ze dvou sloupců: `int32` a `string_` s maximální délkou 10 znaků.


In [10]:
dt = np.dtype([
    ('cele_cislo', np.int32),
    ('text', 'S10')
])

e = np.array([
    (1, b"bruh"),
    (2, b"bro")
], dtype = dt)

8. Naplňte pole `e` hodnotami `[(1, "a"), (2, "b"), (3, "c")]`.


In [12]:
e = np.array([
    [(1, "a"), (2, "b"), (3, "c")]
], dtype = dt)

print(e)

[[(1, b'a') (2, b'b') (3, b'c')]]


9. Změňte hodnotu druhého prvku ve druhém sloupci pole `e` na `"hello"`.


In [13]:
e['text'][0, 1] = b"hello"

print(e)

[[(1, b'a') (2, b'hello') (3, b'c')]]


## 1.2 Vytváření polí

1. Vytvořte matici samých jedniček o rozměrech 3x3 a vypište všechny její prvky.


In [30]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2. Vytvořte vektor s hodnotami od 10 do 49.


In [31]:
vektor = np.arange(10, 50, 1)
vektor

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

3. Vytvořte pole 3x4 typu `bool` se všemi prvky `True`.


In [32]:
pravdy = np.ones((3, 4), dtype = bool)
pravdy

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

4. Vytvořte matici 3x3 s hodnotami od 0 do 8.


In [33]:
A = np.arange(0, 9, 1).reshape(3, 3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5. Vytvořte jednotkovou matici 3x3.


In [34]:
I = np.eye((3), dtype = int)
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

6. Vytvořte pole 3x3x3 s náhodnými hodnotami.


In [39]:
rand_arr = np.random.random(size = (3, 3, 3))
rand_arr

array([[[0.14917293, 0.71889619, 0.30495118],
        [0.12456824, 0.54582777, 0.74509481],
        [0.77064372, 0.69215444, 0.42243147]],

       [[0.27439887, 0.24557323, 0.76546552],
        [0.13375573, 0.15662837, 0.42868338],
        [0.96347795, 0.61799064, 0.48302827]],

       [[0.10400832, 0.55417656, 0.74849995],
        [0.39470027, 0.26617471, 0.51213579],
        [0.21477747, 0.5925844 , 0.26296896]]])

7. Vytvořte 2D pole s 1 na okraji a 0 uvnitř.


In [40]:
n, m = 5, 5
arr = np.zeros((n, m), dtype=int)

arr[0, :] = 1
arr[-1, :] = 1
arr[:, 0] = 1
arr[:, -1] = 1

arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

8. Jak přidat okraj vyplněný nulami kolem existujícího pole?


In [41]:
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
arr

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

9. Vytvořte matici 5x5, kde jediné nenulové prvky jsou `[1, 2, 3, 4]` pod hlavní diagonálou (nápověda: `diagflat`).
```
0 0 0 0 0
1 0 0 0 0
0 2 0 0 0
0 0 3 0 0
0 0 0 4 0
```


In [54]:
mat = np.diagflat([1, 2, 3, 4], -1)
mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

10. Z pole 8x8 samých nul vytvořte pomocí řezů co nejelegantněji šachovnicovou matici 8x8.
```
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
0 1 0 1 0 1 0 1
1 0 1 0 1 0 1 0
```


In [ ]:
sachovnice = np.zeros((8, 8), dtype = int)

sachovnice[::2, 1::2] = 1
sachovnice[1::2, ::2] = 1

sachovnice

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

11. Vytvořte šachovnicovou matici 8x8 pomocí funkce `tile`.


In [58]:
blok = np.array([[0, 1],
                 [1, 0]])

sach = np.tile(blok, (4, 4))

sach

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

12. Vytvořte vektor velikosti 10 s hodnotami v rozsahu od 0 do 1 (obě krajní hodnoty vyloučeny).


In [64]:
s_kraji = np.linspace(0, 1, 12)

bez_kraju = vals[1:-1]

bez_kraju


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

13. Vytvořte strukturované pole s koordináty `x` a `y` pokrývající oblast `[0, 1] x [0, 1]`.


In [65]:
n = 5

x = np.linspace(0, 1, n)
y = np.linspace(0, 1, n)

X, Y = np.meshgrid(x, y)

dtype = np.dtype([('x', float), ('y', float)])

points = np.zeros(X.size, dtype=dtype)
points['x'] = X.ravel()
points['y'] = Y.ravel()

print(points)

[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )
 (0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)
 (0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )
 (0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)
 (0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]


## 1.3 NumPy a práce se soubory

1. Jak načíst následující soubor?
```
1, 2, 3, 4, 5
6, , , 7, 8
, , 9, 10, 11
```


In [66]:
%%writefile test_data.csv
1, 2, 3, 4, 5
6, , , 7, 8
 , , 9,10,11

Writing test_data.csv


In [68]:
data = np.genfromtxt("test_data.csv", delimiter=",")
print(data)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


2. Vytvořte tři náhodné matice 5x5 a uložte je do souboru ve formátu HDF5.


In [70]:
import h5py

A = np.random.rand(5,5)
B = np.random.rand(5,5)
C = np.random.rand(5,5)

with h5py.File("matice.h5", "w") as f:
    f.create_dataset("matrix_A", data=A)
    f.create_dataset("matrix_B", data=B)
    f.create_dataset("matrix_C", data=C)

3. Načtěte soubor z předchozího úkolu, zobrazte obsah každé matice a zjistěte jejich rozměry.


In [71]:
with h5py.File("matice.h5", "r") as f:
    for name in f.keys():
        data = f[name][:]
        print(f"Dataset: {name}")
        print("Obsah matice:\n", data)
        print("Rozměry:", data.shape)
        print("-" * 30)

Dataset: matrix_A
Obsah matice:
 [[0.72423446 0.87853675 0.01195369 0.5424879  0.62637689]
 [0.46861734 0.23256612 0.79254167 0.14355578 0.64906643]
 [0.08587633 0.08385042 0.08431872 0.90920045 0.79016656]
 [0.66708744 0.80601825 0.26830988 0.22518469 0.53008522]
 [0.38725851 0.1381863  0.98026585 0.69514077 0.36968139]]
Rozměry: (5, 5)
------------------------------
Dataset: matrix_B
Obsah matice:
 [[0.85235677 0.11716355 0.07172371 0.14157341 0.35405842]
 [0.331457   0.72106485 0.12918738 0.18481516 0.05842587]
 [0.70517012 0.72971994 0.42000255 0.84404673 0.61928069]
 [0.79852545 0.43094188 0.29312524 0.40472504 0.2575018 ]
 [0.79096446 0.76455846 0.31608008 0.03693536 0.88584878]]
Rozměry: (5, 5)
------------------------------
Dataset: matrix_C
Obsah matice:
 [[0.40118179 0.82718234 0.52247201 0.4723931  0.89982733]
 [0.25964273 0.59402677 0.54923963 0.30430262 0.93005173]
 [0.67289641 0.79739463 0.16264369 0.4042642  0.47282788]
 [0.39101241 0.71323051 0.77321933 0.07453167 0.867