# 1. Úkoly

## 1.1 Indexování a řezání

- Vytvořte NumPy pole s názvem `a` obsahující čísla od 1 do 10.
- Vytvořte 2D NumPy pole s názvem `b` o rozměrech 3x3 a naplňte ho libovolnými čísly.


In [7]:
import numpy as np

a = np.arange(1, 11, 1)

b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


1. Vyberte z pole `a` třetí a čtvrtý prvek.

In [9]:
print(a[2])
print(a[3])

3
4


2. Vyberte z pole `a` všechna sudá čísla.

In [10]:
print(a[1::2])

[ 2  4  6  8 10]


3. Obraťte vektor `a` (první prvek se stane posledním).

In [11]:
a = a[::-1]
print(a)

[10  9  8  7  6  5  4  3  2  1]


4. Vyberte z pole `b` druhý řádek.

In [13]:
print(b[1,:])

[4 5 6]


5. Vyberte z pole `b` diagonální prvky.

In [14]:
print(np.diag(b))

[1 5 9]


6. Změňte hodnotu prvku na druhém řádku, prvním sloupci v `b` na 100.

In [15]:
b[1,0] = 100
b

array([[  1,   2,   3],
       [100,   5,   6],
       [  7,   8,   9]])

7. Vyberte z pole `b` všechny prvky větší než 5.

In [16]:
vyber = b[b > 5]
print(vyber)

[100   6   7   8   9]


8. Vytvořte masku pro pole `b`, která bude `True` pro všechny prvky menší než 3.

In [19]:
maska = b < 3
print(maska)

[[ True  True False]
 [False False False]
 [False False False]]


9. Pomocí masky vyberte z pole `b` všechny prvky menší než 3.

In [20]:
print(b[maska])

[1 2]


## 1.2 View a copy

- Vytvořte NumPy pole s názvem `a` a naplňte ho libovolnými čísly.


In [21]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

1. Pomocí `a` vytvořte proměnnou `b` obsahující řez druhého řádku a všech sloupců pole `a`.

In [23]:
b = a[2, :]
b

array([7, 8, 9])

2. Změňte hodnotu prvního prvku v `b`. Jak se tato změna projeví v `a`?

In [24]:
b[0] = 70
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [70,  8,  9]])

3. Vytvořte proměnnou `c` obsahující **kopii** druhého řádku pole `a`.

In [25]:
c = a[1].copy()
c

array([4, 5, 6])

4. Změňte hodnotu prvního prvku v `c`. Jak se tato změna projeví v `a`?

In [27]:
c[0] = 80
print(c)
print()
print(a)

[80  5  6]

[[ 1  2  3]
 [ 4  5  6]
 [70  8  9]]


5. Zjistěte, zda `b` a `c` sdílí stejná data v paměti.

In [32]:
print(b.base is c)

False


6. Vytvořte proměnnou `d` obsahující diagonální prvky pole `a`.

In [41]:
d = np.diag(a)
d

array([1, 5, 9])

7. Změňte hodnotu prvního diagonálního prvku v `d`. Jak se tato změna projeví v `a`?

In [42]:
d[0] = 54


ValueError: assignment destination is read-only

8. Vytvořte proměnnou `e` obsahující transpozici pole `a`. Ověřte přes atribut `base`, zda jde o kopii, nebo o `view`.

In [44]:
e = a.T
print(e)
print(e.base is a)

[[ 1  4 70]
 [ 2  5  8]
 [ 3  6  9]]
True


## 1.3 Lineární algebra

1. Vynásobte matici 5x3 maticí 3x2 (maticový součin).


In [48]:
m1 = np.array([[n + m * 10 for n in range(3)] for m in range(5)])
m2 = np.array([[n + m * 10 for n in range(2)] for m in range(3)])
print(m1)
print()
print(m2)
print()
print(m1 @ m2)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]
 [40 41 42]]

[[ 0  1]
 [10 11]
 [20 21]]

[[  50   53]
 [ 350  383]
 [ 650  713]
 [ 950 1043]
 [1250 1373]]


2. Vezměte náhodnou matici 10x2 představující kartézské souřadnice a převeďte je na polární souřadnice.

In [62]:
m3 = np.random.randint(1, 11, (2, 10))
m3

x = m3[:, 0]
y = m3[:, 1]

r = np.sqrt(x**2 + y**2)
phi = np.arctan2(y, x)

polar = np.column_stack((r, phi))

print(polar)


[[8.54400375 1.21202566]
 [9.21954446 0.21866895]]


3. Pro dvě pole `X` a `Y` zkonstruujte Cauchyho matici `C` (`C_ij = 1 / (x_i - y_j)`).

In [63]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])

C = 1 / (X[:, None] - Y[None, :])

print(C)

[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


4. Uvažujte náhodné pole tvaru `(100, 2)` reprezentující souřadnice a spočítejte vzdálenost pro každý bod.

In [65]:
nah_pole = np.random.rand(100, 2)

dist = np.sqrt(nah_pole[:, 0]**2 + nah_pole[:, 1]**2)

print(dist)

[0.29490886 1.35844841 0.29703566 1.01948015 0.8397813  0.59202992
 0.84247391 1.31370632 0.74515334 0.47730276 1.02507144 1.17848487
 0.49400046 0.79134469 0.69356175 0.46951252 1.31800083 0.9625834
 0.92097135 0.2637638  0.86027115 1.23176018 0.47825376 0.66514222
 1.28011025 0.68173935 0.864292   0.47144527 0.43641337 1.02399569
 0.58158523 1.03340164 0.39275878 0.92983907 0.21325195 0.99937048
 1.01179743 1.05034296 0.93934332 0.9304601  0.47315211 0.57316736
 0.93718057 1.00207809 0.90131714 0.91990733 0.40548773 0.62181076
 0.88741055 0.34086262 1.14939342 0.8748928  0.48123887 1.03431951
 1.13383211 0.57978417 0.89249297 0.67075513 0.38569269 0.80372061
 0.48444334 0.11071365 0.73636874 0.81894789 1.06417965 1.07974672
 0.9233074  1.26674803 1.093719   0.96204827 0.69434194 0.77921335
 0.89096974 0.63962144 0.83097354 1.14060128 0.87571402 0.60515976
 0.75121598 1.01406916 0.53702394 0.82832563 0.73328378 0.93515847
 0.38861016 0.82487027 0.51040525 0.74622708 0.92741469 0.27703

5. Ověřte empiricky na náhodných maticích, že platí $(AB)^T = B^T A^T$.

In [74]:
A = np.random.randint(1, 11, (3, 4))
B = np.random.randint(1, 11, (4, 5))

print(A)
print(B)
print()

l = (A @ B).T
r = B.T @ A.T

print(l)
print(r)
print()

print(np.allclose(l, r))


[[ 7  3  2  8]
 [10  7  4  1]
 [ 7  6  6  5]]
[[ 3  4  9  1  2]
 [ 7  5  5  2  4]
 [ 4  6  6 10  3]
 [10  7  6  4  9]]

[[130 105 137]
 [111 106 129]
 [138 155 159]
 [ 65  68  99]
 [104  69 101]]
[[130 105 137]
 [111 106 129]
 [138 155 159]
 [ 65  68  99]
 [104  69 101]]

True


6. Pro náhodné 1D vektory $u, v$ vypočítejte dyadický součin $uv$, kde $$(uv)_{ij} = u_i v_j$$, pomocí `newaxis`. Zkontrolujte výsledek s `np.outer(u, v)`.

In [77]:
u = np.random.randint(1, 11, 5)
v = np.random.randint(1, 11, 4)

print(u)
print(v)
print()
uv = u[:, np.newaxis] * v[np.newaxis, :]

uv_kontrola = np.outer(u, v)

print(uv)
print(uv_kontrola)
print()
print(np.allclose(uv, uv_kontrola))

[10  3  5  8  6]
[7 5 1 7]

[[70 50 10 70]
 [21 15  3 21]
 [35 25  5 35]
 [56 40  8 56]
 [42 30  6 42]]
[[70 50 10 70]
 [21 15  3 21]
 [35 25  5 35]
 [56 40  8 56]
 [42 30  6 42]]

True


7. Vypočítejte hodnost matice o velikosti 5x6 naplněné hodnotami 0, 1, 2, 3 ... Byli byste schopni zdůvodnit, proč je hodnost právě taková?

In [80]:
m4 = np.array([[n + m * 6 for n in range(6)] for m in range(5)])
print(m4)

rank = np.linalg.matrix_rank(m4)
print(rank)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
2


## 1.4 Funkce nad poli

1. Vytvořte pole 10x10 s náhodnými hodnotami a najděte minimální a maximální hodnoty.

In [96]:
pole = np.random.randint(1, 101, (10,10))
pole

print(pole)

max = pole.max()
min = pole.min()

print(max, min)

[[47 21 89 80 72 57  5 88 11 21]
 [21 22 55 91 36 31 67 78 81 66]
 [57 16 42 37 81 21 86 29 53  2]
 [41 92 14 29 56 95 98 28 35 38]
 [24 52 27 63  4 16 64 94  4 61]
 [15 34 47 63 90 43 58 56 88 97]
 [25 50 84 86 97 71 64 26 63 87]
 [23 21 18  7 88  8 19 26 10 98]
 [92 72 92 54 31 10 89  3 91 85]
 [ 8 35 37 56 47 96 19 15 45 72]]
98 2


2. Vytvořte náhodný vektor o velikosti 30 a najděte střední hodnotu.

In [97]:
nah_v = np.random.randint(1, 31, 30)
print(nah_v.mean())

15.8


3. Uvažujme celočíselný vektor `Z`. Které z těchto výrazů jsou platné?
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [105]:
Z = np.array([1, 2 , 3, 4])

Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

4. Jaký je výsledek následujícího výrazu?
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [109]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


5. Jaké jsou výsledky následujících výrazů?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [110]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\vitek\AppData\Local\Temp\ipykernel_40008\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\vitek\AppData\Local\Temp\ipykernel_40008\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\vitek\AppData\Local\Temp\ipykernel_40008\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


6. Jak najít společné (stejné) hodnoty mezi dvěma poli?

In [111]:
pole1 = np.array([1, 2, 3, 4, 5])
pole2 = np.array([3, 4, 5, 6, 7])

shoda = np.intersect1d(pole1, pole2)
print(shoda)

[3 4 5]


7. Jak vypočítat `((A+B) * (-A/2))` přímo v poli (bez kopírování)?

In [113]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=float)
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]], dtype=float)

np.add(A, B, out=B)      # B = A + B
np.divide(A, -2, out=A)  # A = -A/2
np.multiply(B, A, out=B) # B = (A+B) * (-A/2)

print(B)

[[ -5. -10. -15.]
 [-20. -25. -30.]
 [-35. -40. -45.]]


8. Vytvořte náhodný vektor o velikosti 10 a seřaďte ho.

In [121]:
vek = np.array(np.random.randint(1, 11, 10))
print(vek)
print(np.sort(vek))

[ 6 10  6  5  3  3  2  4  1  6]
[ 1  2  3  3  4  5  6  6  6 10]


9. Vezměte daný vektor: jak přidat 1 ke každému prvku indexovanému druhým vektorem (pozor na opakované indexy)?

In [125]:
dany_vektor = np.array([1, 2, 3, 4, 5])

indexy = np.array([1, 3, 1, 4, 1])

np.add.at(dany_vektor, indexy, 1)

print(dany_vektor)

[1 5 3 5 6]
