# 1. Indexování a řezání v NumPy

V tomto notebooku projdeme:
- základní indexování 1D a 2D polí,
- řezání (slicing),
- výběr pomocí pole indexů,
- maskování,
- přiřazování do výřezů.


Zdroj inspirace:
- [Lectures on scientific computing with Python](http://github.com/jrjohansson/scientific-python-lectures)
- [numerical_python_course](https://gitlab.com/coobas/numerical_python_course)


## 1.1 Import knihovny NumPy

Nejdřív importujeme `numpy` pod obvyklou zkratkou `np`.


In [1]:
import numpy as np


## 1.2 Základní indexování a řezání

Řezání (slicing) funguje v NumPy stejně jako u seznamů.


In [2]:
vector = np.linspace(0, 3, 7)
print(vector)
print(vector[1])
print(vector[1:4])
print(vector[1:4:2])


[0.  0.5 1.  1.5 2.  2.5 3. ]
0.5
[0.5 1.  1.5]
[0.5 1.5]


U vícerozměrného pole adresujeme jednotlivé dimenze čárkou. Například `a[1, 2]` je prvek na druhém řádku a třetím sloupci (indexujeme od nuly).

In [3]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)
print(matrix[0, 1])
print(matrix[0, :])
print(matrix[:, 1])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3]
[2 5 8]


Pokud zadáme řez pro řádky i sloupce, dostaneme podmatici splňující obě podmínky.

In [4]:
print(matrix[0:2, 1:3])


[[2 3]
 [5 6]]


Když jeden index vynecháme, NumPy vrátí řez o jeden rozměr nižší. Tady dostaneme řádek:

In [5]:
matrix[1]


array([4, 5, 6])

Stejný výsledek dostaneme i zápisem s `:`.

In [6]:
matrix[1, :]


array([4, 5, 6])

Druhý sloupec:

In [7]:
matrix[:, 1]


array([2, 5, 8])

In [8]:
matrix[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Do indexovaných výřezů můžeme také přiřazovat hodnoty.

In [9]:
matrix[0, 0] = -10
print(matrix)


[[-10   2   3]
 [  4   5   6]
 [  7   8   9]]


Funguje to i pro více prvků. Máme dvě možnosti:
- přiřadit jednu hodnotu (broadcasting),
- přiřadit pole stejného tvaru jako cílový výřez.


In [10]:
matrix[1, :] = 0
print(matrix)


[[-10   2   3]
 [  0   0   0]
 [  7   8   9]]


In [11]:
matrix[:, 2] = np.array([1, 2, 3])
print(matrix)

[[-10   2   1]
 [  0   0   2]
 [  7   8   3]]


## 1.3 Další možnosti řezání

U syntaxe `a[od:do:krok]` můžeme používat i záporné indexy a záporný krok. Například:
- `a[-1]` je poslední prvek,
- `a[-2]` je předposlední prvek,
- `a[:-1]` je vše kromě posledního prvku,
- `a[::-1]` je pole v opačném pořadí.

Stejné principy platí i pro seznamy.


In [12]:
vector = np.arange(1, 10)
print(vector[-1])
print(vector[-3:])
print(vector[::-1])
print(vector[-5::-1])

9
[7 8 9]
[9 8 7 6 5 4 3 2 1]
[5 4 3 2 1]


## 1.4 Indexace pomocí pole indexů a masek

Kromě řezů můžeme vybírat prvky i pomocí pole indexů.

In [13]:
vector = np.arange(1, 10)
vyber = np.array([5, 2, 1, 8])
print(vector)
print(vector[vyber])


[1 2 3 4 5 6 7 8 9]
[6 3 2 9]


Pole indexů může obsahovat i záporné hodnoty (počítají se od konce) a indexy se mohou opakovat.

In [14]:
vyber = np.array([-3, -2, -1, 6, 7, 8])
print(vector)
print(vector[vyber])

[1 2 3 4 5 6 7 8 9]
[7 8 9 7 8 9]


Pokud indexace obsahuje hodnotu mimo rozsah, dostaneme chybu.

Následující buňka je záměrná výuková chyba.

In [15]:
vyber = np.array([1, 2, 10])
print(vector)
print(vector[vyber])

[1 2 3 4 5 6 7 8 9]


IndexError: index 10 is out of bounds for axis 0 with size 9

Stejný princip funguje i pro matici.

In [16]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
vyber_x = np.array([0, 1, 2])
vyber_y = np.array([1, 2, 0])
print(matrix)
print("---")
print(matrix[vyber_x, vyber_y])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
---
[2 6 7]


Všimněte si, že výsledkem není matice, ale vektor prvků určených dvojicemi souřadnic.

Indexační pole proto musí mít stejnou délku.

Následující buňka je záměrná výuková chyba.

In [17]:
vyber_x = np.array([0, 1, 2])
vyber_y = np.array([1, 0])
print(matrix[vyber_x, vyber_y])


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

### 1.4.1 Maskování

Pole můžeme indexovat i pomocí masky (`True`/`False`). Maska musí mít:
- stejný tvar jako pole, nebo
- délku odpovídající jedné dimenzi pole.

Výsledkem jsou jen prvky (nebo celé řádky/sloupce), pro které je v masce `True`.


In [18]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask = np.array([[True, False, True], [False, True, False], [True, False, True]])
print(mask)
print(matrix[mask])


[[ True False  True]
 [False  True False]
 [ True False  True]]
[1 3 5 7 9]


In [19]:
mask = np.array([True, False, True])
print(matrix[mask, :])
print(matrix[:, mask])

[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]
