# 1. Lineární algebra v NumPy

Nejdřív importujeme `numpy` pod obvyklou zkratkou `np`.


In [1]:
import numpy as np


## 1.1 Proč vektorizovat

NumPy je navržené pro efektivní práci s vektory, maticemi a obecně n-rozměrnými poli. Kdykoli to jde, je vhodné formulovat výpočty přes vektorové a maticové operace místo explicitních smyček v Pythonu.


## 1.2 Operace se skaláry

Pole můžeme násobit, dělit, sčítat i odčítat skalárem.

In [5]:
v1 = np.arange(0, 5)
v1


array([0, 1, 2, 3, 4])

In [6]:
v1 * 2


array([0, 2, 4, 6, 8])

In [7]:
v1 + 2


array([2, 3, 4, 5, 6])

In [8]:
np.ones((3, 3)) / 4


array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])

## 1.3 Operace po prvcích

Operátory jako `+`, `-`, `*`, `/` fungují pro pole standardně po prvcích. Nejde tedy o maticové násobení.


In [9]:
m1 = np.array([[n + m * 10 for n in range(5)] for m in range(5)])
m1


array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [10]:
m1 * m1


array([[   0,    1,    4,    9,   16],
       [ 100,  121,  144,  169,  196],
       [ 400,  441,  484,  529,  576],
       [ 900,  961, 1024, 1089, 1156],
       [1600, 1681, 1764, 1849, 1936]])

In [11]:
v1 * v1


array([ 0,  1,  4,  9, 16])

## 1.4 Broadcasting

Broadcasting popisuje, jak NumPy zarovnává tvary polí při aritmetických operacích. Menší pole se podle pravidel rozšíří přes větší pole tak, aby byly tvary kompatibilní.

Podrobnosti jsou v dokumentaci:
https://numpy.org/doc/stable/user/basics.broadcasting.html


In [12]:
v1.shape, m1.shape


((5,), (5, 5))

Výsledek bude mít tvar `m1.shape`.

In [13]:
m1 * v1


array([[  0,   1,   4,   9,  16],
       [  0,  11,  24,  39,  56],
       [  0,  21,  44,  69,  96],
       [  0,  31,  64,  99, 136],
       [  0,  41,  84, 129, 176]])

## 1.5 Maticová algebra

Maticové násobení pro `ndarray` dělá funkce `np.dot` nebo operátor `@` ([PEP 465](https://peps.python.org/pep-0465/)).


In [14]:
v1 = np.arange(0, 5)
m1 = np.array([[n + m * 10 for n in range(5)] for m in range(5)])
print(v1)
print(m1)


[0 1 2 3 4]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [15]:
# maticové násobení dvou matic
np.dot(m1, m1)


array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [16]:
m1 @ m1


array([[ 300,  310,  320,  330,  340],
       [1300, 1360, 1420, 1480, 1540],
       [2300, 2410, 2520, 2630, 2740],
       [3300, 3460, 3620, 3780, 3940],
       [4300, 4510, 4720, 4930, 5140]])

In [17]:
# maticové násobení vektoru a matice
np.dot(m1, v1)


array([ 30, 130, 230, 330, 430])

In [18]:
# skalární součin
v1 @ v1


np.int64(30)

## 1.6 Transformace a komplexní čísla

Pro transpozici můžeme použít `.T`, `transpose()` nebo `np.transpose()`. U komplexních čísel se hodí také `conjugate()`.


In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A.T)
print(A.transpose())
print(np.transpose(A))

In [ ]:
# transpozice je view
print(id(A))
B = A.T
print(id(B.base))

In [ ]:
C = np.array([[1j, 2j], [3j, 4j]])
C


In [ ]:
np.conjugate(C)      # nebo C.conjugate()


In [ ]:
# Hermitovské sdružení
C.conjugate().T


In [ ]:
# conjugate() vrací nové pole (nejde o view na původní data)
print(id(C))
B = C.conjugate()
print(B.base is C)

Reálnou a imaginární část získáme přes `real` a `imag` (funkce nebo atributy):

In [ ]:
np.real(C)


In [ ]:
C.imag


Komplexní číslo můžeme rozložit na absolutní hodnotu a úhel pomocí `abs` a `angle`.

In [ ]:
print(np.angle(C))
# výsledek je v radiánech a všechny hodnoty byly čistě komplexní
print(np.angle(C+1))


In [ ]:
np.abs(C + 1)


## 1.7 Základní funkce lineární algebry

V NumPy je modul `linalg`. Pro pokročilejší lineární algebru se často používá SciPy.

Inverzi matice spočítáme funkcí `linalg.inv`.

In [19]:
m2 = np.array([[1., 1.5], [-1, 2]])
m2


array([[ 1. ,  1.5],
       [-1. ,  2. ]])

In [20]:
np.linalg.inv(m2)


array([[ 0.57142857, -0.42857143],
       [ 0.28571429,  0.28571429]])

In [21]:
# toto by měla být jednotková matice
np.linalg.inv(m2) @ m2


array([[1., 0.],
       [0., 1.]])

`linalg.det` vypočítá determinant.

In [22]:
np.linalg.det(m2)


np.float64(3.5)

`linalg.eig` vypočítá vlastní čísla a vlastní vektory matice.

In [23]:
D, U = np.linalg.eig(m2)
print(D)
print(U)

[1.5+1.11803399j 1.5-1.11803399j]
[[0.77459667+0.j         0.77459667-0.j        ]
 [0.25819889+0.57735027j 0.25819889-0.57735027j]]


`linalg.svd` vypočítá singulární rozklad matice.

In [24]:
M = np.arange(12).reshape(3, 4)
print(M)

U, S, V = np.linalg.svd(M)
print(U)
print(S)
print(V)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0.1473065   0.90090739  0.40824829]
 [ 0.50027528  0.2881978  -0.81649658]
 [ 0.85324407 -0.32451178  0.40824829]]
[2.24092982e+01 1.95534034e+00 7.68985043e-16]
[[ 0.39390139  0.46087474  0.5278481   0.59482145]
 [-0.73813393 -0.29596363  0.14620666  0.58837696]
 [-0.50775138  0.52390687  0.47544042 -0.4915959 ]
 [-0.20539847  0.65232016 -0.68844492  0.24152322]]
